name: Leona
options:
  bundleIdPrefix: com.leona
  deploymentTarget:
    iOS: "17.0"
  xcodeVersion: "15.0"
  generateEmptyDirectories: true

settings:
  base:
    SWIFT_VERSION: "5.9"
    MARKETING_VERSION: "1.0.0"
    CURRENT_PROJECT_VERSION: 1
    DEVELOPMENT_TEAM: HLUMLG6SWA
    CODE_SIGN_STYLE: Automatic
    INFOPLIST_FILE: Leona/Info.plist
    CODE_SIGN_ENTITLEMENTS: Leona/Leona.entitlements
    ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
    ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME: AccentColor
    TARGETED_DEVICE_FAMILY: "1,2"
    SUPPORTS_MACCATALYST: false
    IPHONEOS_DEPLOYMENT_TARGET: "17.0"

targets:
  Leona:
    type: application
    platform: iOS
    sources:
      - path: Leona
        excludes:
          - "**/*.xcassets"
          - "Resources/**"
      - path: Leona/Resources
        type: folder
      - path: Leona/Resources/Assets.xcassets
        type: file
    resources:
      - path: Leona/Resources/Assets.xcassets
      - path: Leona/Resources/WHO
      - path: Leona/Localization
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.leona.app
        PRODUCT_NAME: Leona
    entitlements:
      path: Leona/Leona.entitlements
    info:
      path: Leona/Info.plist
